# https://www.netlifycms.org/docs/git-gateway-backend/.
backend:
  name: git-gateway
  branch: content

# https://www.netlifycms.org/docs/configuration-options/#publish-mode.
publish_mode: editorial_workflow

# https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders.
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

# https://www.netlifycms.org/docs/add-to-your-site/#collections.
collections:
  - name: "actualite"
    label: "Actualite"
    folder: "content/actualite"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "title", name: "Title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
